In [1]:
import numpy as np

In [2]:
## How to convert a list into a array..

In [3]:
l = [1,2,3,4,5]

In [5]:
arr = np.array(l)

In [6]:
## Check the type of this array

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [13]:
## ndim funtion is teel you what is a dimension of a particular array.
arr.ndim

1

In [14]:
arr1.ndim

2

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
## How I able to plot or vizulise this particular array


In [23]:
## Inside numpy will you be able to find out another function called as numpy.matrix
mat = np.matrix(l)  ## Matrix is basically a subclass of an array inside a numpy 

In [24]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [25]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
a = arr

In [28]:
a

array([1, 2, 3, 4, 5])

In [29]:
arr

array([1, 2, 3, 4, 5])

In [39]:
arr[0] = 100  ## this kind of data copy opertion is basically called as a Salocopy operation..
## Its does not copy the data it is give the referances of data

In [37]:
arr

array([100,   2,   3,   4,   5])

In [38]:
a

array([100,   2,   3,   4,   5])

In [44]:
b = np.copy(arr)  ## This is the concept of deepcopy or Salocopy 
##  when ever call numpy.copy then asign a values so it will create a seprate memory where it is going to copy this one to the next memory then it will give the reference memory eqal to b ..both the data set completly different ..it is not going to affect to each other at any point of time..

In [45]:
b

array([100,   2,   3,   4,   5])

In [46]:
b[0] = 234

In [47]:
b

array([234,   2,   3,   4,   5])

In [48]:
arr

array([100,   2,   3,   4,   5])

In [49]:
## Inside numpy will you be able to find out multiple function by which will create different different kind of array

In [50]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [51]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [54]:
list(i*i for i in range(5)) ## it will be generate a some type of data for me 

[0, 1, 4, 9, 16]

In [58]:
iterable = (i*i for i in range(5))

In [59]:
np.fromiter(iterable,float)  ## using fromiter function to generate a some data

array([ 0.,  1.,  4.,  9., 16.])

In [60]:
np.fromstring('23 45 56',sep = ' ')

array([23., 45., 56.])

In [61]:
np.fromstring('23,45,56',sep = ',')

array([23., 45., 56.])

In [62]:
arr

array([100,   2,   3,   4,   5])

In [63]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [64]:
## there are couple of funtion which wiil be able to find out applicable or see some type of information about array

In [65]:
arr.ndim

1

In [66]:
arr1.ndim

2

In [68]:
arr.size ## size is tell you total number of element 

5

In [69]:
arr1.size

6

In [70]:
arr.shape

(5,)

In [71]:
arr1.shape

(2, 3)

In [72]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [73]:
arr.dtype

dtype('int64')

In [74]:
arr1.dtype

dtype('int64')